[package]
name = "tester"
version = "0.1.0"
authors = ["lixiangmin01 <lixiangmin01@baidu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory   = "0.1.6" # needed by testing

testing = { path = ".." }
